### ISSUE TITLE
Commercial license for tnm4j lib

### ISSUE THREAD

**Issue by VovaKorzh** [soulwing/tnm4j#18]
Hello, Carl Harris
I did not found any other way to reach you, so I will ask my question here.
Is there is any possibility of licensing this lib for commercial use?
GNU GPL does not fit with my company's third-Party software usage policy.

**Comment by ceharris** [comment]
In seven years or so, I've received only one other query about commercial licensing, so there hasn't been sufficient demand to warrant the costs associated with simply creating and managing a commercial license.

I deliberately selected the GPL because it is the same license used by the "bundled" SNMP and MIB providers (snmp4j and mibble) for their open source offerings, so as to reduce the likelihood that users of this library would inadvertently use it in ways that might violate the licensing terms of its dependencies. 

That said, I am willing consider a change to a different license that would be more compatible with potential commercial use.

**Comment by The-Funk** [comment]
Carl,

I was also looking for a way to contact you and couldn't find one. I'm using tnm4j in one of my business projects. Really cool stuff! I know this isn't the place for it but just wanted to thank you for a great library! You made working with SNMP fun.

-Cole

**Comment by ceharris** [comment]
Thanks Cole! I really appreciate the feedback.
